server:
  port: 8093

spring:
  application:
    name: pgpayment

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/pg_payment_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j:
  retry:
    instances:
      billingKeyTokenRetrieve:
        max-attempts: 2
        wait-duration: 200ms
        retry-exceptions:
          - feign.RetryableException
          - java.net.SocketTimeoutException
          - java.net.ConnectException

      cardPaymentInquire:
        max-attempts: 2
        wait-duration: 300ms
        retry-exceptions:
          - feign.RetryableException
          - java.net.SocketTimeoutException
          - java.net.ConnectException

      cardPreApprovalInquire:
        max-attempts: 2
        wait-duration: 300ms
        retry-exceptions:
          - feign.RetryableException
          - java.net.SocketTimeoutException
          - java.net.ConnectException

  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true
        record-exceptions:
          - feign.RetryableException
          - feign.FeignException
          - java.net.SocketTimeoutException
          - java.net.ConnectException
    instances:
      billingKeyTokenRetrieve:
        base-config: default
      cardPaymentApprove:
        base-config: default
      cardPreApprovalRequest:
        base-config: default
      cardPaymentCancel:
        base-config: default
      cardPreApprovalCancel:
        base-config: default
      cardPaymentInquire:
        base-config: default
      cardPreApprovalInquire:
        base-config: default
