server:
  port: 8093

spring:
  application:
    name: pgpayment

  datasource:
    url: jdbc:mysql://localhost:3308/pg_payment_db
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true