package com.erumpay.pgpayment.domain.enums;

public enum PgFailureCode {
    BILLING_KEY_LOOKUP_FAILED,
    BILLING_KEY_CIRCUIT_OPEN,
    CARD_REQUEST_FAILED,
    CARD_TIMEOUT_UNCONFIRMED,
    CARD_CIRCUIT_OPEN,
    LEDGER_SAVE_FAILED,
    COMPENSATION_CANCEL_FAILED,
    COMPENSATION_VOID_FAILED
}
