package com.erumpay.pgpayment.domain.enums;

public enum PgFailureCode {
    BILLING_KEY_LOOKUP_FAILED,
    BILLING_KEY_CIRCUIT_OPEN,
    CARD_REQUEST_FAILED,
    CARD_RESULT_UNKNOWN,
    CARD_AUTH_ONLY_FAILED,
    CARD_AUTH_ONLY_RESULT_UNKNOWN,
    CARD_CANCEL_FAILED,
    CARD_CANCEL_RESULT_UNKNOWN,
    CARD_VOID_FAILED,
    CARD_VOID_RESULT_UNKNOWN,
    CARD_TIMEOUT_UNCONFIRMED,
    CARD_CIRCUIT_OPEN,
    LEDGER_RECOVERY_REQUIRED,
    RECONCILIATION_RETRY_EXHAUSTED,
    LEDGER_SAVE_FAILED,
    COMPENSATION_CANCEL_FAILED,
    COMPENSATION_VOID_FAILED
}
